# templates/mkdocs.yml

site_name: 'Problem Solving with Python'
site_description: 'Website companion for the book Problem Solving with Python 3.8 Edition by Peter D. Kazarinoff'
site_author: 'Peter D. Kazarinoff'
repo_url: 'https://github.com/ProfessorKazarinoff/Problem-Solving-with-Python-38-Edition'

# Plugins
plugins:
  - mknotebooks:
      execute: true
      preamble: "preamble.py"
      write_markdown: true
  - search

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'cyan'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - instant
  icon:
    logo: material/school

# Markdown Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex

# Javascript for MathJax
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Extra css
extra_css:
  - 'stylesheets/extra.css'

# Theme Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProfessorKazarinoff
      name: ProfessorKazarinoff on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pkazarinoff
      name: pkazarinoff on Twitter

# Copyright
copyright: 'Text Licensed Under Creative Commons Attribution-ShareAlike 4.0'

# Content
nav:
  - Home: index.ipynb
  - Preface:
    - Motivation: 00-Preface/00-01-Motivation.ipynb
    - Acknowledgments: 00-Preface/00-02-Acknowledgments.ipynb
    - Supporting Materials: 00-Preface/00-03-Supporting-Materials.ipynb
    - Formatting Conventions: 00-Preface/00-04-Formatting-Conventions.ipynb
    - Errata: 00-Preface/00-05-Errata.ipynb
  - Chapter 1 Orientation:
    - 1.1 Introduction: 01-Orientation/01-00-Orientation.ipynb
    - 1.2 Why Python?: 01-Orientation/01-01-Why-Python.ipynb
    - 1.3 The Anaconda Distribution of Python: 01-Orientation/01-02-The-Anaconda-Distribution-of-Python.ipynb
    - 1.4 Installing Anaconda on Windows: 01-Orientation/01-03-Installing-Anaconda-on-Windows.ipynb
  - Chapter 3 The Python REPL:
    - 3.1 Introduction: 03-The-Python-REPL/03-01-Introduction.ipynb
    - 3.2 Python as a Calculator: 03-The-Python-REPL/03-02-Python-as-a-Calculator.ipynb
    - 3.3 The Python REPL: 03-The-Python-REPL/03-03-Variables.ipynb
    - 3.4 String Operations: 03-The-Python-REPL/03-04-String-Operations.ipynb
    - 3.5 Print Statements: 03-The-Python-REPL/03-05-Print-Statements.ipynb
    - 3.6 Summary: 03-The-Python-REPL/03-06-Summary.ipynb
    - 3.7 Review Questions: 03-The-Python-REPL/03-07-Review-Questions.ipynb
  - Chapter 4 Data Types and Variables:
    - 4.1 Introduction: 04-Data-Types-and-Variables/04-01-Introduction.ipynb
    
  - Chapter 10 Symbolic Math:
    - 10.1 Introduction: 10-Symbolic-Math/10-00-Introduction.ipynb
    - 10.2 SymPy: 10-Symbolic-Math/10-01-SymPy.ipynb
    - 10.3 Installing SymPy: 10-Symbolic-Math/10-02-Installing-SymPy.ipynb
    - 10.4 Defining Variables: 10-Symbolic-Math/10-03-Defining-Variables.ipynb
    - 10.5 Expressions and Substitutions: 10-Symbolic-Math/10-04-Expressions-and-Substitutions.ipynb
    - 10.6 Equations: 10-Symbolic-Math/10-05-Equations.ipynb
    - 10.7 Solving Equations: 10-Symbolic-Math/10-06-Solving-Equations.ipynb
    - 10.8 Solving Two Equations for Two Unknows: 10-Symbolic-Math/10-07-Solving-Two-Equations-for-Two-Unknowns.ipynb
    - 10.9 Summary: 10-Symbolic-Math/10-08-Summary.ipynb
    - 10.10 Review Questions: 10-Symbolic-Math/10-09-Review-Questions.ipynb
